# .github/workflows/formal.yml
# Automatically apply formatting when pushing to main.
name: Format

on:
  push:
    branches: [ "main" ] # Only runs when code is pushed to the 'main' branch

env:
  DEFAULT_PYTHON: "3.12"

jobs:
  auto_format:
    name: Ruff Auto-formatting
    runs-on: ubuntu-latest

    permissions:
      contents: write # Needed for stefanzweifel/git-auto-commit-action to push changes

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Needed for auto-commit action to work reliably

      - name: Set up Python ${{ env.DEFAULT_PYTHON }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}

      - name: Install Ruff
        run: |
          python -m pip install --upgrade pip
          pip install ruff

      - name: Run Ruff Format and Apply Changes
        # This command applies formatting changes in-place.
        # Output is shown in the logs.
        run: ruff format .

      - name: Check for formatting changes
        id: git_status
        run: |
          git_status=$(git status --porcelain)
          echo "::set-output name=has_changes::$(if [ -n "$git_status" ]; then echo "true"; else echo "false"; fi)"
          echo "Git status (after formatting):"
          git status

      - name: Commit and Push changes
        if: steps.git_status.outputs.has_changes == 'true'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Fix(format): Apply Ruff formatting [skip ci]" # '[skip ci]' prevents infinite loops
          branch: ${{ github.ref_name }} # Push back to the 'main' branch


      - name: Run Ruff Lint Check
        # By default, astral-sh/ruff-action runs 'ruff check'.
        # We don't need to specify 'args: "check"' explicitly unless we want other check options.
        uses: astral-sh/ruff-action@v3
        # No 'args' needed if just running default 'ruff check'
        # with:
        #   args: "check --fix-only" # Example: to only show fixes and error if changes are found
        # continue-on-error: true # Uncomment if you want the workflow to pass even if linting fails
        
